import string
import itertools as it


def format_string(string):
    """Format string to normalize spaces."""
    operators = ['+', '-', '*', '/', '=', '(', ')']

    # Remove all spaces in input string.
    string = string.replace(' ', '')

    # Add spaces around operators.
    for operator in operators:
        string = string.replace(operator, " " + operator + " ")

    # Special case for exponentiation. Fix spaces added as a result of *
    # being found. Also convert ^ to **.
    string = string.replace('*  *', '**')
    string = string.replace('^', '**')

    return string.lower()


def gen_puzzle_solutions(input_string):
    """Solves symbolic puzzles for all basize math operations."""
    string = format_string(input_string)

    # Get lead chars to check for lead 0's later.
    lead_chars = set(x[0] for x in string.split() if x.isalpha())

    # Complete set of unique chars found in the input string.
    char_set = set(x for x in string if x.isalpha())

    # Check to ensure that input string does not contain more than 10 unique
    # Characters.
    if len(char_set) > 10:
        print("Invalid input string, too many distinct letters.")
        raise StopIteration

    # Get permutations of numbers limited by the size of the char_set.
    for nums in it.permutations('0123456789', len(char_set)):
        char_dict = dict(zip(char_set, nums))

        # Check for leading zeros.
        if '0' not in [char_dict[x] for x in lead_chars]:
            expression = string

            # Replace symbols with numbers generated by permutations call.
            for key in char_dict:
                expression = expression.replace(key, char_dict[key])

            # Separate the expression into left and right sides.
            LHS, RHS = expression.split('=')

            # Evaluate the expression if possible.
            try:
                if eval(LHS) == eval(RHS):
                    yield expression
            except (ArithmeticError, SyntaxError):
                pass


def main():
    print(*gen_puzzle_solutions('SEND + MORE = MONEY'), sep='\n')


if __name__ == '__main__':
    main()
